### ISSUE TITLE
sklearn error

### ISSUE THREAD

**Issue by HOWARD201314** [vztu/VIDEVAL_release#1]
1. scikit-learn 0.20.3 cannot be installed in python3.8 enviroment
2. when install scikit-learn latest version, when execute program it generate error about sklearn and joblib

please tell me which env you use! thanks you!

**Comment by vztu** [comment]
Thanks for your interest! 

I used python 3.6.7 with sklearn 0.20.3. What kind of error about sklearn and joblib occurred?
