### ISSUE TITLE
Please give a “requirements.txt” file in the python section

### ISSUE THREAD

**Issue by Power-Z** [vztu/VIDEVAL_release#12]
Please give a “requirements.txt” in the python section，the versions of sklearn and numpy have been incorrect，thank you.

**Comment by Power-Z** [comment]
OK, I have solved this problem. The version of my package is as follows：
python == 3.6
scikit-learn == 0.21.2
numpy == 1.19.2
scipy == 1.5.2

**Comment by vztu** [comment]
Thanks! The version I used was:
python=3.6.7
scikit-learn=0.20.3
numpy=1.16.2
scipy=1.4.1
