### ISSUE TITLE
Can run in Octave?

### ISSUE THREAD

**Issue by lovekittynine** [vztu/VIDEVAL_release#2]
Thanks for your great works! Can this model run in Octave not in Matlab?

**Comment by lovekittynine** [comment]
Another question, which dataset the provided pretrained weights used? If it not trained on combined dataset, and could you please provide pretrained weights which are trained on combined dataset? Thanks very much!

**Comment by vztu** [comment]
> Thanks for your great works! Can this model run in Octave not in Matlab?

- Thanks for your interest! We haven't tried anything on Octave, since all the dependency IQA models are exclusively implemented in MATLAB. So we strongly suggest you use MATLAB and Python 3.


> Another question, which dataset the provided pretrained weights used? If it not trained on combined dataset, and could you please provide pretrained weights which are trained on combined dataset? Thanks very much!

- The pre-trained model is already trained on the combined dataset.

**Comment by osamagharbi** [comment]
Thank you very much for your grea work, it is very helpful, I want to test the model on other datasets can you please guide me how to test the pretrained model on my videos and how to retrain it on my dataset please ?, thanks in advance!
