### ISSUE TITLE
Library not loaded: @loader_path/libmex.dylib

### ISSUE THREAD

**Issue by SuperFreeMan-CXM** [vztu/VIDEVAL_release#5]
When I run demo_compute_VIDEVAL_feats.m, there is an error:
dlopen(/Users/XXX/VIDEVAL_release/include/matlabPyrTools/corrDn.mexmaci64,
6): Library not loaded: @loader_path/libmex.dylib

Can you give me some help?

**Comment by SuperFreeMan-CXM** [comment]
Can you tell me what's your matlab version.

**Comment by vztu** [comment]
Hi we have tested >=MATLAB 2018 on both Linux and Windows and it works fine. We only observed there are warnings and was much slower on Windows system. 

We recommended you to run it on Linux or ~~Mac OS~~.

**Comment by SuperFreeMan-CXM** [comment]
I can not figure out this problem yet, my system is macos Catalina 10.15.7.
I try MATLAB 2018a and MATLAB 2019b, both them exist this problem.

**Comment by vztu** [comment]
Sorry I have my friend tested in Mac and we also observed this problem. 

Could you try compiling the `corrDn.c` file using MATLAB's [`mex`](https://www.mathworks.com/help/matlab/ref/mex.html?s_tid=srchtitle) command? It seems the pre-compiled `corrDn.mexmaci64` provided by the author didn't work.

**Comment by SuperFreeMan-CXM** [comment]
Unfortunately, a new error occurred when I use `mex corrDn.c` .

Error message:
Undefined symbols for architecture x86_64:
  "_internal_reduce", referenced from:
      _mexFunction in corrDn.o
  "_internal_wrap_reduce", referenced from:
      _mexFunction in corrDn.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

It seems that the program can't support MAC system.

**Comment by vztu** [comment]
Hi I sincerely appreciate your findings! I'd add a note in README saying that MAC system will have errors. 

I don't have a MAC machine, nor do I have experience in working with `mex` functions. Sorry that I can't help with this bug. The workaround is that you need to run on Linux/Windows. 

The whole problem is with [`FRIQUEE`](https://github.com/vztu/VIDEVAL_release/blob/5bc4cd3d3773481ea6083740ca57ee9dadab6983/include/calc_VIDEVAL_feats.m#L400) features that depend on `matlabPyrTools` lib, which is a pretty old lib. I haven't got a time to update these old dependencies; instead, I just include all the initial implementations as is. It means that the `FRIQUEE` release in this [link](https://live.ece.utexas.edu/research/Quality/index_algorithms.htm) cannot support MAC system neither.

**Comment by SuperFreeMan-CXM** [comment]
Thanks for your work, I will try to run on windows.Sometimes some old dependent libraries are always troublesome. 👍
