### ISSUE TITLE
Will you release a python-version?

### ISSUE THREAD

**Issue by Sissuire** [vztu/VIDEVAL_release#8]
Thanks for the sharing. Do you have the plan to release a python version of this code ?

**Comment by vztu** [comment]
Hi thanks for your interest! This implementation re-used codes from many other models like BRISQUE, GMLOG, FRIQUEE, TLVQM, which are all written in MATLAB. Thus, it is a big load to re-implement them all in Python and we're not planning to release any other versions, unfortunately.

**Comment by Sissuire** [comment]
@vztu Thanks. That is a big load certainly.

**Comment by DerrickXuNu** [comment]
Matlab is enough I think

**Comment by vztu** [comment]
@DerrickXuNu Matlab is all you need
