### ISSUE TITLE
Results on the H265 codec videos

### ISSUE THREAD

**Issue by liuyunzhuo** [vztu/VIDEVAL_release#9]

**Comment by liuyunzhuo** [comment]
Dr. Tu, thanks for your excellent work in the new BVQA Model. 
I tried this method on 6 H265 codec videos. The tiny datasets contains 3 scenes, and  Each scene was compressed at two different H265 bitrates, details as follows:

video_name,mos,width,height,pixfmt,framerate,bitdepth
0001_anshi_1920x1080_bitrate1024_period50.265,3,1920,1080,yuvj420p,25,8,
0001_anshi_1920x1080_bitrate2048_period50.265,2.5,1920,1080,yuvj420p,25,8,
0002_yuanqu_jinjing_jingzhi_1920x1080_bitrate1024_period50.265,4,1920,1080,yuvj420p,25,8,
0002_yuanqu_jinjing_jingzhi_1920x1080_bitrate2048_period50.265,4,1920,1080,yuvj420p,25,8,
0003_huiyishi_1920x1080_bitrate1024_period50.265,3,1920,1080,yuvj420p,25,8,
0003_huiyishi_1920x1080_bitrate2048_period50.265,3.5,1920,1080,yuvj420p,25,8,
* the mos scores is not correctly, I just used my own perceptual sense

I used your pretrained VIDEVAL model and am pleasantly surprised by the results, details as follows:
-Scene 1 low bitrates 4.354653518241946131
-Scene 1 high bitrates 4.354734656467440956
-Scene 2 low bitrates 4.347848240390886687
-Scene 2 high bitrates 4.360306543913059940
-Scene 3 low bitrates 4.394886534758546404
-Scene 3 high bitrates 4.404795760613800404

As you can see, the model seems can detect the tiny diffent quality changes caused by bitrates. To be honest, I cant't tell the difference by my own eyes. 

Should I retrain the Model with more correct mos scores, and use more datas,(maybe 30 scenes and each scenes with 2different bitrates). Will it work on the compression artifact problem?
 
I'm very looking forward to your reply!

**Comment by vztu** [comment]
Hi @liuyunzhuo, thanks for your interest!

VIDEVAL was pretrained on UGC datasets that mostly contain UGC distortions (please see our paper for explanations). If you manually check the videos in these datasets, they rarely contain compression artifacts; instead, real distortions introduced while capturing like camera motions, low resolution, low-light are more dominant. In this sense, VIDEVAL was trained to predict these distortions better than compression artifacts. In fact, (pretrained) VIDEVAL was not performing well on traditional compression datasets such as LIVE-VQA. It needs to be re-trained on compression datasets.

Also, if you cannot tell the difference with your own eyes, the model was likely to fail as well. Maybe you can try to use a much larger QP and test again.

**Comment by liuyunzhuo** [comment]
Thanks for your kind reply！

Our videos are all caputured by stable survillence camera. So,  there are no camera motions, low resoulution like UGC does. Maybe the two artifacts are from compression and Breathing Effect. If I score the MOS for these videos using standards like Youtube datasets does, I think that all this videos will be score high.  I will take a little experiment---- using the pretrained VIDEVAL on our bigger datasets to test if the model can distinguish the difference between the "both-high-quality". 

However I think it's difficult to get the groundtruth MOS about our own high quality datasets.Is it a right way to score the video using stricter assessment criteria and assessed by professional people to get larger range of MOS?  When scroing the videos, If people consider about some commpression artifacts and breathing effect，then train model using the dataset which is generated on this criteria. Can the Model give its score also considering the compression artifacts and breathing effect?

**Comment by liuyunzhuo** [comment]
Thanks for your kind reply！

Our videos are all caputured by stable survillence camera. So,  there are no camera motions, low resoulution like UGC does. Maybe the two artifacts are from compression and Breathing Effect. If I score the MOS for these videos using standards like Youtube datasets does, I think that all this videos will be score high.  I will take a little experiment---- using the pretrained VIDEVAL on our bigger datasets to test if the model can distinguish the difference between the "both-high-quality". 

However I think it's difficult to get the groundtruth MOS about our own high quality datasets.Is it a right way to score the video using stricter assessment criteria and assessed by professional people to get larger range of MOS?  When scroing the videos, If people consider about some commpression artifacts and breathing effect，then train model using the dataset which is generated on this criteria. Can the Model give its score also considering the compression artifacts and breathing effect?

**Comment by vztu** [comment]
In my opinion, your problem might be better formulated as a full-reference VQA problem rather than NR/Blinds VQA. You'd better try some full-reference VQA models (like [VMAF](https://github.com/Netflix/vmaf) or [SpEED](https://github.com/utlive/SpEED)) first. Full-reference models are usually more accurate than NR ones for compression artifacts, like in your scenario. 

If the perceptual differences in your database are small, you can try to use [2AFC](https://en.wikipedia.org/wiki/Two-alternative_forced_choice) pair comparison for your subjective study, which might be better than single stimulus studies.
